apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  labels:
    app: mysql-config-map
data:
  MYSQL_DB_HOST_1: mysql1-service
  MYSQL_DB_HOST_2: mysql2-service
  MYSQL_DB_HOST_3: mysql3-service
  MYSQL_DB_1: topeducation_db_1
  MYSQL_DB_2: topeducation_db_2
  MYSQL_DB_3: topeducation_db_3